/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smartlibrary;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prana
 */
public class BookIssue extends javax.swing.JFrame {

    ResultSet rs, rsd;
    PreparedStatement pst;
    Connect cObj = new Connect();
    Connection con = cObj.dbConnect();
    
    EmailUtil eobj = new EmailUtil();

    /* 
    String gMail = "jjjjj@gmail.com" ;
    String subject = "JAVA PROJECT" ;
    String messageString = "New test message, \nThis is a test mail.";
    EmailUtil eobj = new EmailUtil();
    int a = eobj.sendEmail(gMail, subject, messageString);
    */
    
    public void bookIssueLoad()
    {
    //Code for loading table from database to jTable1
        int c;
        try {
            pst = con.prepareStatement("select * from bookIssue");
            rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i = 1; i<=c; i++)
                {
                    v2.add(rs.getString("issueId"));
                    v2.add(rs.getString("memberID"));
                    v2.add(rs.getString("bookID"));
                    v2.add(rs.getString("issueDate"));
                    v2.add(rs.getString("returnDate"));
                    v2.add(rs.getString("returned_on"));
                    v2.add(rs.getString("fine"));
                }
                d.addRow(v2);
            }
         /*/   pst=con.prepareStatement("select count(bookIssueID) from bookIssues");
            ResultSet rs1 = pst.executeQuery();
            rs1.next();
            int count = rs1.getInt("count(bookIssueID)");
            tfcount.setText(String.valueOf(count));*/
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * Creates new form BookIssue
     */
    public BookIssue() {
        initComponents();
        bookIssueLoad();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfmid = new javax.swing.JTextField();
        tfbid = new javax.swing.JTextField();
        tfidate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        tfrdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfrondate = new javax.swing.JTextField();
        tffine = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK ISSUE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Member id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Issue id");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Book id");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Issue date");

        tfidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Issue_id", "Member_id", "Book_id", "Issue date", "Return date", "Returned on", "Fine"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tfid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfidMouseClicked(evt);
            }
        });
        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });
        tfid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfidKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Add");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 72));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        tfrdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Return date");

        tfrondate.setText("0000-00-00");
        tfrondate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrondateActionPerformed(evt);
            }
        });

        tffine.setText("0.0");
        tffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffineActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Returned on");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Fine");

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("T");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setText("T");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfmid)
                                        .addComponent(tfbid)
                                        .addComponent(tfrdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tfidate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2)))
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfrondate, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(tffine))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfrdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfrondate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tffine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidateActionPerformed

    private void tfidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfidMouseClicked
        jButton1.setEnabled(false); //Helps to avoid accidental duplication.
    }//GEN-LAST:event_tfidMouseClicked

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed

    }//GEN-LAST:event_tfidActionPerformed

    private void tfidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfidKeyReleased
        // The following code segment is for searching usinng bookIssueID.
        try
        {
            String sql = "select * from bookIssue where issueID = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, tfid.getText());
            rs = pst.executeQuery();
            if(rs.next())
            {
                String s1 = rs.getString("memberID");
                String s2 = rs.getString("bookID");
                String s3 = rs.getString("issueDate");
                String s4 = rs.getString("returnDate");
                String s5 = rs.getString("returned_on");
                String s6 = rs.getString("fine");
                tfmid.setText(s1);
                tfbid.setText(s2);
                tfidate.setText(s3);
                tfrdate.setText(s4);
                tfrdate.setText(s5);
                tfrdate.setText(s6);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tfidKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Code lines for insertion/adding new rows :
        String mid = tfmid.getText();
        String bid = tfbid.getText();
        String idate = tfidate.getText();
        String rdate = tfrdate.getText();
        String rondate = tfrondate.getText();
        String fine = tffine.getText();
        if(!mid.equals("") && !bid.equals("") && !idate.equals("") && !rdate.equals(""))
        {
            int k=0;
            try {
                pst = con.prepareStatement("insert into bookIssue(memberID, bookID, issueDate, returnDate, returned_on, fine) values(?,?,?,?,?,?)  "/*"insert into bookIssues(bookIssueID, bookIssueName)values(?,?)  "*/)  ;
                pst.setString(1, mid);
                pst.setString(2, bid);
                pst.setString(3, idate);
                pst.setString(4, rdate);
                pst.setString(5, rondate);
                pst.setString(6, fine);
                try{
                    k = pst.executeUpdate();
                }
                catch(Exception e){
                    System.out.println(e);
                }
                if(k==1)
                {
                    JOptionPane.showMessageDialog(this,"Book issue recorded");
                    tfid.setText("");
                    tfmid.setText("");
                    tfbid.setText("");
                    tfidate.setText("");
                    tfrdate.setText("");
                    tfrondate.setText("");
                    tffine.setText("");
                    tfmid.requestFocus();
                    bookIssueLoad();
                    
                    /***** Send mail *****/
                    try{
                    pst = con.prepareStatement("select emailID from Members where memberID = ? ");
                    pst.setString(1, mid);
                    rs = pst.executeQuery();  
                    rs.next(); 
                    //You are positioning the cursor before the first row and then requesting data.
                    //You need to use rs.next() to move the cursor to the first row.
                    //Else we get: java.sql.SQLException: Before start of result set .
                    
                    
                    String mailIdOnissue = rs.getString("emailID");
                    String mailSubOnissue = "Book issued from Sree Buddha Library.";
                    pst = con.prepareStatement("select bookName from books where bookID = ? ");
                    pst.setString(1, bid);
                    rs = pst.executeQuery();   
                    rs.next();
                    String bookName = rs.getString("bookName");
                    String mailTextOnissue = "Dear member,"
                            + "\nThe book \""+bookName+"\" has been issued to you."
                            + "\nIssue date: "+idate+""
                            + "\nReturn date: "+rdate;
                    int b = eobj.sendEmail(mailIdOnissue, mailSubOnissue, mailTextOnissue);
                    }
                    
                    catch (SQLException ex) 
                    {
                        Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    /**********/
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error");
                }
            }
            catch (SQLException ex)
            {
                Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Enter required information.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Update button
        String id = tfid.getText();
        String mid = tfmid.getText();
        String bid = tfbid.getText();
        String idate = tfidate.getText();
        String rdate = tfrdate.getText();
        String rondate = tfrondate.getText();
        String fine = tffine.getText();
        if(!mid.equals("") && !bid.equals("") && !idate.equals("") && !rdate.equals("") && !id.equals(""))
        {
            int k=0;
            try {
                pst = con.prepareStatement("update bookIssue set memberID = ?, bookID = ?, issueDate = ?, returnDate = ?, returned_on = ?, fine = ? where issueID = ? ")  ;
                pst.setString(1, mid);
                pst.setString(2, bid);
                pst.setString(3, idate);
                pst.setString(4, rdate);
                pst.setString(5, rondate);
                pst.setString(6, fine);
                pst.setString(7, id);
                try
                {
                    k = pst.executeUpdate();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                if(k==1)
                {
                    JOptionPane.showMessageDialog(this,"Book issue record updated");
                    tfid.setText("");
                    tfmid.setText("");
                    tfbid.setText("");
                    tfidate.setText("");
                    tfrdate.setText("");
                    tfrondate.setText("");
                    tffine.setText("");
                    tfmid.requestFocus();
                    bookIssueLoad();
                    jButton1.setEnabled(true);
                    
                    if(!rondate.equals("0000-00-00")){
                        /***********************************************/
                    try 
                    {
                        pst = con.prepareStatement("select * from bookIssue where bookid = ? ");
                        pst.setString(1, bid);
                        rsd = pst.executeQuery();
                        rsd.next();
                        String returndate = rsd.getString("returnDate");
                        String retondate = rsd.getString("Returned_on");
                        Date parsedDate1 = null;                            
                        Date parsedDate2 = null;                            
                        try 
                        {
                            parsedDate1 = new SimpleDateFormat("yyyy-MM-dd").parse(returndate);
                            parsedDate2 = new SimpleDateFormat("yyyy-MM-dd").parse(retondate);
                        }
                        catch (ParseException ex) 
                        {
                            Logger.getLogger(DueDateNotify.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Date d1 = null;
                        Date d2 = null;
                        d1 = parsedDate1;
                        d2 = parsedDate2;
                        long diff = d2.getTime() - d1.getTime();
                        TimeUnit time = TimeUnit.DAYS;
                        long difference = time.convert(diff, TimeUnit.MILLISECONDS);
                        System.out.println("\nThe difference in days is : "+difference+"\n");  
                        double newfine=0;
                        if(difference>=0){
                            newfine = 0.5 * difference ;
                        }
                        pst = con.prepareStatement("update bookIssue set fine= ? where issueid = ?");
                        pst.setDouble(1, newfine);
                        pst.setString(2, id);
                        pst.executeUpdate();

                    }
                    catch (SQLException ex) 
                    {
                        Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("SQLException");
                    }
                        bookIssueLoad();
                    
                        /***********************************************/
                        BookAvailMail obj = new BookAvailMail();
                        obj.availMail(bid);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error");
                }

            } catch (SQLException ex) {
                Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Select a Book issue record");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Delete button
        String id = tfid.getText();
        if(!id.equals(""))
        {
            int k=0;
            try
            {
                pst = con.prepareStatement("Delete from bookIssue where IssueId = ? ")  ;
                pst.setString(1,id);
                try
                {
                    k = pst.executeUpdate();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                if(k==1)
                {
                    JOptionPane.showMessageDialog(this,"Book issue record deleted");
                    tfid.setText("");
                    tfmid.setText("");
                    tfbid.setText("");
                    tfidate.setText("");
                    tfrdate.setText("");
                    tfrondate.setText("");
                    tffine.setText("");
                    tfmid.requestFocus();
                    bookIssueLoad();
                    jButton1.setEnabled(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Error");
                }
            }
            catch (SQLException ex)
            {
                Logger.getLogger(BookIssue.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Select a bookIssue");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Cancel button
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Reset button
        tfid.setText("");
        tfmid.setText("");
        tfbid.setText("");
        tfidate.setText("");
        tfrdate.setText("");
        tfrondate.setText("0000-00-00");
        tffine.setText("0.0");
        tfmid.requestFocus();
        jButton1.setEnabled(true);
        bookIssueLoad();//jTable1.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // This comboBox helps to avoid wasteage of time caused by unnecessary mouse click on tfid which disables the add button.
        tfid.setText("NEW ENTRY");
        jButton1.setEnabled(true);
        tfrondate.setText("0000-00-00");
        tffine.setText("0.0");


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();       
        tfid.setText((d1.getValueAt(selectIndex, 0)).toString());
        tfmid.setText((d1.getValueAt(selectIndex, 1)).toString());
        tfbid.setText((d1.getValueAt(selectIndex, 2)).toString());
        tfidate.setText((d1.getValueAt(selectIndex, 3)).toString());
        tfrdate.setText((d1.getValueAt(selectIndex, 4)).toString());
        tfrondate.setText((d1.getValueAt(selectIndex, 5)).toString());
        tffine.setText((d1.getValueAt(selectIndex, 6)).toString());
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void tfrdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrdateActionPerformed

    private void tffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffineActionPerformed

    private void tfrondateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrondateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrondateActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String str = sdf.format(date);
        tfrondate.setText(str);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String str = sdf.format(date);
        tfidate.setText(str);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookIssue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfbid;
    private javax.swing.JTextField tffine;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfidate;
    private javax.swing.JTextField tfmid;
    private javax.swing.JTextField tfrdate;
    private javax.swing.JTextField tfrondate;
    // End of variables declaration//GEN-END:variables
}
